### PR TITLE
HTML attributes 'required' and 'autofocus' for input field

### PR DESCRIPTION
**Pull request by alexlanz**
Provide to possibility to set the HTML attributes 'required' and 'autofocus' on the input field using Vue properties.

### CODE REVIEW

**Comment by krilor** [comment]
Hey Alex.
Thanks for the PR - nice suggestion! Any chance you have the time to also add these two new props to the readme?

**Comment by alexlanz** [comment]
Sure!! I have updated the readme.

**Comment by alexlanz** [comment]
Hi,
I just want to ask if the pull request is now ok or if you need any other changes?

**Comment by krilor** [comment]
Hey Alex.
Sorry for not merging sooner - I'm traveling at the moment.
Thanks for the update (and the PR in general). I'll bump the npm version next week when I get back home.
Cheers!

**Pull request merged**
